name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: scheme-basic
      - name: Compile LaTeX document
        run: which pdflatex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with: 
          name: waves
          path: waves.pdf
